# Generated by Django 6.0.6 on 2026-06-23 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='hide_until_due',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='last_occurrence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='next_occurrence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notification_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence_type',
            field=models.CharField(choices=[('NONE', 'Nenhuma'), ('DAILY', 'Diária'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual'), ('CUSTOM', 'Personalizada')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo_api.tasklist'),
        ),
    ]
