# Generated by Django 6.0.6 on 2026-06-23 16:54

from django.db import migrations

def create_default_list(apps, schema_editor):
    TaskList = apps.get_model('todo_api', 'TaskList')
    Task = apps.get_model('todo_api', 'Task')
    
    my_tasks_list, created = TaskList.objects.get_or_create(
        name='My Tasks',
        defaults={'color': '#3b82f6'}
    )
    
    # Assign all tasks without a list to "My Tasks"
    Task.objects.filter(task_list__isnull=True).update(task_list=my_tasks_list)

class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_tasklist_task_hide_until_due_task_is_starred_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_list),
    ]
