# Generated by Django 6.0.6 on 2026-06-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_auto_20260623_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.CharField(blank=True, choices=[('5_MINUTES', '5 minutos'), ('15_MINUTES', '15 minutos'), ('30_MINUTES', '30 minutos'), ('1_HOUR', '1 hora'), ('2_HOURS', '2 horas')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluída'), ('ARCHIVED', 'Arquivada')], default='PENDING', max_length=20),
        ),
    ]
